<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"奖惩类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiangchengdengji"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"评语类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueqipingyu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学科管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueshengchengji"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"奖惩登记管理",
                        "menuJump":"列表",
                        "tableName":"jiangchengdengji"
                    }
                ],
                "menu":"奖惩登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师评价管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshiCommentback"
                    }
                ],
                "menu":"教师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"信息反馈管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"信息反馈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学期评语管理",
                        "menuJump":"列表",
                        "tableName":"xueqipingyu"
                    }
                ],
                "menu":"学期评语管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生成绩管理",
                        "menuJump":"列表",
                        "tableName":"xueshengchengji"
                    }
                ],
                "menu":"学生成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生档案管理",
                        "menuJump":"列表",
                        "tableName":"xueshengdangan"
                    }
                ],
                "menu":"学生档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资助记录管理",
                        "menuJump":"列表",
                        "tableName":"xueshengzizhu"
                    }
                ],
                "menu":"资助记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"学生管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"奖惩登记管理",
                        "menuJump":"列表",
                        "tableName":"jiangchengdengji"
                    }
                ],
                "menu":"奖惩登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"教师评价管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshiCommentback"
                    }
                ],
                "menu":"教师评价管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学期评语管理",
                        "menuJump":"列表",
                        "tableName":"xueqipingyu"
                    }
                ],
                "menu":"学期评语管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生成绩管理",
                        "menuJump":"列表",
                        "tableName":"xueshengchengji"
                    }
                ],
                "menu":"学生成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生档案管理",
                        "menuJump":"列表",
                        "tableName":"xueshengdangan"
                    }
                ],
                "menu":"学生档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资助记录管理",
                        "menuJump":"列表",
                        "tableName":"xueshengzizhu"
                    }
                ],
                "menu":"资助记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"学生管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"教师",
        "tableName":"jiaoshi"
    }
    ,
		{
	        "backMenu":[
	            {
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"奖惩登记管理",
	                        "menuJump":"列表",
	                        "tableName":"jiangchengdengji"
	                    }
	                ],
	                "menu":"奖惩登记管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看",
	                            "新增",
	                            "删除"
	                        ],
	                        "menu":"教师评价管理",
	                        "menuJump":"列表",
	                        "tableName":"jiaoshiCommentback"
	                    }
	                ],
	                "menu":"教师评价管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看",
	                            "新增",
	                            "删除"
	                        ],
	                        "menu":"信息反馈管理",
	                        "menuJump":"列表",
	                        "tableName":"liuyan"
	                    }
	                ],
	                "menu":"信息反馈管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"公告信息管理",
	                        "menuJump":"列表",
	                        "tableName":"news"
	                    }
	                ],
	                "menu":"公告信息管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"学期评语管理",
	                        "menuJump":"列表",
	                        "tableName":"xueqipingyu"
	                    }
	                ],
	                "menu":"学期评语管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"学生成绩管理",
	                        "menuJump":"列表",
	                        "tableName":"xueshengchengji"
	                    }
	                ],
	                "menu":"学生成绩管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"学生档案管理",
	                        "menuJump":"列表",
	                        "tableName":"xueshengdangan"
	                    }
	                ],
	                "menu":"学生档案管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"资助记录管理",
	                        "menuJump":"列表",
	                        "tableName":"xueshengzizhu"
	                    }
	                ],
	                "menu":"资助记录管理"
	            }
	        ],
	        "frontMenu":[
	
	        ],
	        "roleName":"学生",
	        "tableName":"yonghu"
	    }
];

var hasMessage = '';
